### ISSUE TITLE
While trying to parse the command line args in lstm_tutorial.py: line 14-17 getting error:

### ISSUE THREAD

**Issue by SrGrace** [adventuresinML/adventures-in-ml-code#12]
> usage: ipykernel_launcher.py [-h] [--data_path DATA_PATH] run_opt
ipykernel_launcher.py: error: argument run_opt: invalid int value: 'C:\\Users\\Sourav\\AppData\\Roaming\\jupyter\\runtime\\kernel-15d13538-092b-4243-bed1-ed8946e08bc4.json'
An exception has occurred, use %tb to see the full traceback.

>SystemExit: 2

>C:\Users\Sourav\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py:2855: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

Could you please help me on this? Thanks!

**Comment by hlumin** [comment]
It looks like you are running it from a jupyter notebook, while the program still expects some command line arguments. (line 14 - 17)
```python
parser = argparse.ArgumentParser()
parser.add_argument('run_opt', type=int, default=1, help='An integer: 1 to train, 2 to test')
parser.add_argument('--data_path', type=str, default=data_path, help='The full path of the training data')
args = parser.parse_args()
```
You should be able to fix that by getting rid of the parser and filling args directly instead of getting it from parse_args
